import { MenuItem, CategoryInfo, RestaurantMetadata } from './types';

export const RESTAURANT_INFO: RestaurantMetadata = {
  name: 'Wow Burger',
  tagline: 'Savor the WOW factor in every single bite.',
  location: 'Sabiyan, Dire Dawa, Ethiopia',
  placeDetail: 'Right across from the main Sabiyan Terminal building, a cozy industrial-chic corner styled in rich cream tones.',
  phone: '+251 986 671 224',
  workingHours: 'Every day: 10:00 AM - 11:00 PM',
};

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'burgers',
    name: 'Specialty Burgers',
    icon: '🍔',
    description: '100% premium beef and golden crispy chicken handcrafted with artisan sauces on freshly toasted brioche.',
  },
  {
    id: 'sides',
    name: 'Crispy Sides',
    icon: '🍟',
    description: 'Perfect companion snacks, golden-fried to order and seasoned with fresh herbs and localized spices.',
  },
  {
    id: 'drinks',
    name: 'Chilled Refreshments',
    icon: '🥤',
    description: 'Authentic layered Ethiopian juice blends, milkshakes, and sparkling fresh fruit infusions.',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'wow-classic-cheese',
    name: 'Wow Classic Cheeseburger',
    category: 'burgers',
    description: 'Our award-winning signature hamburger. Perfectly seared grass-fed beef patty layered with double melted cheddar, home-pickled cucumbers, crispy red onion rings, green leaf lettuce, and a rich schmear of house-made mustard mayo on a butter-toasted sesame brioche bun.',
    ingredients: [
      'Artisanal Grilled Beef Patty (150g)',
      'Double American Melted Cheddar',
      'House-Cured Cucumber Pickles',
      'Crisp Red Onion Rings',
      'Fresh Garden Butterhead Lettuce',
      'Toasted Artisanal Sesame Brioche Bun',
      'Wow Secret Signature Remoulade Cream',
    ],
    price: 320,
    image: '/src/assets/images/wow_classic_burger_1781365097615.jpg',
    isPopular: true,
    prepTime: '10-12 mins',
    isSpicy: false,
    isVegetarian: false,
    calories: '610 kcal',
  },
  {
    id: 'sabiyan-spicy-chicken',
    name: 'Sabiyan Spicy Chicken Burger',
    category: 'burgers',
    description: 'Paying homage to the heat of the city! Boldly spiced zinger crispy buttermilk chicken breast completely glazed with spicy local chili honey, topped with fiery jalapeño rounds, molten pepper jack cheese, cool micro-shredded head lettuce, and heavy chipotle cream.',
    ingredients: [
      'Crispy Zinger Chicken Breast',
      'Hot Awaze Chili Honey Glaze',
      'Fresh Sliced Jalapeño Rings',
      'Molten Pepper Jack Cheese Blend',
      'Cool Shredded Cabbage & Lettuce Mix',
      'Toasted Glossy Sweet Brioche Bun',
      'Smoky Chipotle Herb Aioli',
    ],
    price: 380,
    image: '/src/assets/images/sabiyan_spicy_burger_1781365110639.jpg',
    isPopular: true,
    prepTime: '12-15 mins',
    isSpicy: true,
    isVegetarian: false,
    calories: '680 kcal',
  },
  {
    id: 'wow-tower-double',
    name: 'Wow Double Supreme Tower',
    category: 'burgers',
    description: 'Designed for absolute burger connoisseurs. Two seared premium ground beef patties seasoned with house salt, loaded with caramelized sweet sugar balsamic onions, double gooey molten gouda cheese, ripe vine tomatoes, crisp green fields, and our rich smoky brown drippy sauce.',
    ingredients: [
      'Two 150g Premium Ground Beef Patties',
      'Melty Traditional Gouda Cheese Layers',
      'Slow-Caramelized Sweet Balsamic Onions',
      'Orchard Red Vine Tomato Slices',
      'Fresh Crisp Greenleaf Lettuce',
      'Toasted Artisanal Buttered Brioche Bun',
      'Dripping Smoky BBQ Mustard Sauce',
    ],
    price: 480,
    image: '/src/assets/images/wow_hero_burger_1781365083360.jpg',
    isPopular: true,
    prepTime: '15 mins',
    isSpicy: false,
    isVegetarian: false,
    calories: '920 kcal',
  },
  {
    id: 'garden-harvest-veggie',
    name: 'The Garden Smashed Cream Veggie',
    category: 'burgers',
    description: 'An absolute plant-based masterpiece. Smashed slow-cooked chickpea & organic sweet potato base crusted with premium toasted oats, topped with silky cool mashed salted avocado, field baby spinach, griddled light halloumi cheese, and fresh cilantro lime herbal yoghurt on brioche.',
    ingredients: [
      'Slow-Smashed Chickpea & Sweet Potato Patty',
      'Griddled Salted Halloumi Cheese Slice',
      'Toasted Crunchy Oat Batter Crust',
      'Fresh Creamy Salted Avocado Purée',
      'Freshly Squeezed Cilantro Lime Greek Yogurt',
      'Crispy Baby Spinach & Rocket Greens',
      'Soft Honey Wheat Brioche Bun',
    ],
    price: 295,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=800&auto=format&fit=crop',
    isPopular: false,
    prepTime: '12 mins',
    isSpicy: false,
    isVegetarian: true,
    calories: '510 kcal',
  },
  {
    id: 'crispy-sea-salt-fries',
    name: 'Artisanal Golden Sea Salt Fries',
    category: 'sides',
    description: 'Our hand-cut thick-slice Russet potatoes fried twice to a perfect crisp deep golden exterior while remaining fluffy on the inside. Dusted generously with premium coarse gray Brittany sea salt and served in a paper cone with cold herb dipping sauce.',
    ingredients: [
      'Fresh Hand-Cut Russet Potatoes',
      'Twice-Cooked Sunflower Oil Fry',
      'Coarse Grey Brittany Sea Salt Drizzle',
      'Fresh Sprigs of Flat-Leaf Parsley',
      'Chilled Creamy Roasted Garlic Dipping Sauce',
    ],
    price: 150,
    image: '/src/assets/images/sides_fries_combo_1781365126023.jpg',
    isPopular: true,
    prepTime: '6-8 mins',
    isSpicy: false,
    isVegetarian: true,
    calories: '380 kcal',
  },
  {
    id: 'dire-dawa-spiced-wedges',
    name: 'Dire Dawa Awaze Spiced Wedges',
    category: 'sides',
    description: 'Country-style skin-on chunky potato wedges seasoned with our proprietary spice blend, featuring authentic fermented Awaze chili pepper flakes, slow-roasted garlic powder, and sweet paprika. Baked crispy & finished over high heat.',
    ingredients: [
      'Organic Skin-on Russet Potato Wedges',
      'Proprietary Awaze Chili & Paprika Rub',
      'Dry-Roasted Garlic Powder infusion',
      'Crushed Dried Ethiopian Cardamom (Korerima)',
      'Creamy Zesty Lemon Aioli Dip',
    ],
    price: 180,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?q=80&w=800&auto=format&fit=crop',
    isPopular: false,
    prepTime: '10 mins',
    isSpicy: true,
    isVegetarian: true,
    calories: '410 kcal',
  },
  {
    id: 'ethiopian-classic-spriis',
    name: 'Traditional Layered Spriis Juice',
    category: 'drinks',
    description: 'A genuine taste of Ethiopia. Perfectly layered, vibrant cold beverage made from 100% fresh solid puréed fruits—silky-smooth local organic Haas avocado, followed by sun-ripened sweet yellow mango, and finished with refreshing papaya nectar, crowned with a fresh key lime wedge.',
    ingredients: [
      'Thick Fresh Whipped Haas Avocado Paste',
      'Luscious Ripe Puréed Sweet Mango',
      'Sweet Wild Papaya Squeezed Juice',
      'Fragrant Local Key Lime Wedge Squeeze',
      'A light drizzle of Organic Wild Honey',
    ],
    price: 120,
    image: '/src/assets/images/ethiopian_spriis_drink_1781365143964.jpg',
    isPopular: true,
    prepTime: '5 mins',
    isSpicy: false,
    isVegetarian: true,
    calories: '240 kcal',
  },
  {
    id: 'fresh-citrus-punch',
    name: 'Sabiyan Fresh Squeezed Citrus',
    category: 'drinks',
    description: 'An incredibly invigorating cold juice blend made from freshly hand-squeezed orchard-fresh seasonal Sabiyan oranges and tart local lines, served over clear artisan ice blocks for a crisp and completely natural thirst-quenching dessert drink.',
    ingredients: [
      'Fresh-Press Sweet Sabiyan Oranges',
      'Tangy Hand-Squeezed Key Limes',
      'Pure Cold-Pressed Sugar Cane Drops',
      'Fragrant Fresh Mint Sprigs',
      'Block Ice Cubes',
    ],
    price: 100,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?q=80&w=800&auto=format&fit=crop',
    isPopular: false,
    prepTime: '4 mins',
    isSpicy: false,
    isVegetarian: true,
    calories: '120 kcal',
  },
  {
    id: 'wow-chocolate-shake',
    name: 'Wow Triple Cream Chocolate Shake',
    category: 'drinks',
    description: 'Ultimate indulgent thick shake. Premium Dutch dark cacao ice cream whipped long with cold whole dairy milk, topped off with a mountainous plume of fresh real whipped heavy cream, sweetened caramel drizzle, and fine shavings of direct-trade dark chocolate.',
    ingredients: [
      'Premium Dutch Dark Cacao Custard Ice Cream',
      'Chilled Creamery Whole Pasteurised Milk',
      'Heavy Double-Whipped Madagascar Vanilla Cream',
      'Artisanal Warm Caramel Drizzle',
      'Grateful Shavings of Fine 70% Dark Chocolate',
    ],
    price: 180,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop',
    isPopular: true,
    prepTime: '5 mins',
    isSpicy: false,
    isVegetarian: true,
    calories: '490 kcal',
  },
];
